### ISSUE TITLE
How to build FLEXE project?

### ISSUE THREAD

**Issue by KeFan-USTC** [WellingtonLobato/flexe#1]
Dear Mr lobato:
         After reading your paper:FLEXE: Investigating Federated Learning in Connected Autonomous Vehicle Simulations, I want to import your FLEXE project in my omnetpp. But I don't know how to do it. Would you please provide some importing steps in detail？
         I will appreciate it if I can receive your reply!

**Comment by WellingtonLobato** [comment]
This is excellent news. I'm glad you read my paper and want to implement something with Flexe.

I will prepare a step-by-step tutorial to install this version. In general, if you are using Linux, you must install OpenCV (Some information can be seen here: https://docs.opencv.org/4.5.5/) and import the project into your OmNet++.

Also, I'm working on a newer version of Flexe. We will update the repository as soon as the most recent publication is released.

Best regards,

**Comment by KeFan-USTC** [comment]
> This is excellent news. I'm glad you read my paper and want to implement something with Flexe.
> 
> I will prepare a step-by-step tutorial to install this version. In general, if you are using Linux, you must install OpenCV (Some information can be seen here: https://docs.opencv.org/4.5.5/) and import the project into your OmNet++.
> 
> Also, I'm working on a newer version of Flexe. We will update the repository as soon as the most recent publication is released.
> 
> Best regards,

Thank you for your suggestion ，I am looking forward to your later tutorial！

**Comment by WellingtonLobato** [comment]
Hi again!

I've just made some adjustments to the Flexe page. Now, you have more information about how install this new version. Fell free to ask again if you have any issue.

Best regards,
