### ISSUE TITLE
Question about Veins version compatibility

### ISSUE THREAD

**Issue by nagacharan-tangirala** [WellingtonLobato/flexe#3]
Thanks for building this tool and making this available!

I am trying to run the demo example in omnetpp, running into veins errors. I am using the latest master/main branches of veins and flexe. The error message is: 

`flexe/application/MLApp.cc:150:48: error: no member named 'getVehicleId' in 'veins::TraCICommandInterface::Vehicle'
            std::string sendID = traciVehicle->getVehicleId() + ";" + std::to_string(self);
                                 ~~~~~~~~~~~~  ^
flexe/application/MLApp.cc:152:18: error: no member named 'setSpeed' in 'veins::DemoSafetyMessage'
            bsm->setSpeed(traciVehicle->getSpeed());`

It makes me think that the version of veins I am using is not appropriate. I ran Veins demo scenario and can confirm that it is working. I don't know what I am missing here. Appreciate your help!

**Comment by WellingtonLobato** [comment]
Hello! Thank you very much for (trying) to use flexe!!

I believe it is due to some functions that I added to veins. I will share them in the attachment.
[veins-veins-5.2.zip](https://github.com/user-attachments/files/16582603/veins-veins-5.2.zip)

Best regards,

**Comment by nagacharan-tangirala** [comment]
Hey, thanks for the quick response! I can start the simulations with the attached version of veins.

**Comment by WellingtonLobato** [comment]
That's great! I'm going to close the topic. I'll update the version as soon as I finish my PhD!
