### ISSUE TITLE
some question about FLEXE project

### ISSUE THREAD

**Issue by LiHongyuan1** [WellingtonLobato/flexe#4]
Dear WellingtonLobato:
After reading your paper:FLEXE: Investigating Federated Learning in Connected Autonomous Vehicle Simulations. this is wonderful and  i want reproduce your paper result . but have some confuse about this :
**Q1:  FLEXE  and PYFLEX project is install based on windows  or linux ?**  
Q2:  In readme : The project was partitioned into two, one of which is responsible for vehicle-to-vehicle communication ([Flexe] and the other for the construction and training of models  ([PYFlexe] . 
 **i'm not sure how to create connection for two project .** 
A:  running flexe  firstly ,then running PYFLEX   
B : running flexe  firstly  , running some result , then close flexe .  finally , running pyflexe  
which guess is right ?
thanks for your feedback.

**Comment by WellingtonLobato** [comment]
Hi! @LiHongyuan1! First of all, thank you very much for reading the Flexe article and trying to use it. I appreciate you trying to reproduce the results obtained by the experiments. This makes me very happy!
To answer your questions:
Q1: FLEXE and PYFLEX project is install based on windows or linux ?
The installation is based on Linux. I tried to make a Windows version, but I only got good results with OmNet++ installed together with WSL (Windows Subsystem for Linux). I recommend installing it using Ubuntu and OmNet++ version 5.7

Q2: In readme : The project was partitioned into two, one of which is responsible for vehicle-to-vehicle communication ([Flexe] and the other for the construction and training of models ([PYFlexe] .
i'm not sure how to create connection for two project .
PyFlexe is responsible for training the models and Flexe is the vehicle communication part, as you mentioned. In the original article, I used openCV to create the models, you can access this version, it is still available on my github. However, in the most recent version, I use GRPC to connect PyFlexe with Flexe and use one part in Python and the other in Veins.

To run the project, you first need to run PyFlexe (server.py) and then Flexe. It is important that they are configured on the same port.

**Comment by WellingtonLobato** [comment]
I will make a new update of the codes during this week. I am finishing an article about the new version of Flexe and I will make the new codes available, I believe it can solve some problems of running Flexe and PyFlexe together.

**Comment by LiHongyuan1** [comment]
> Hi! @LiHongyuan1! First of all, thank you very much for reading the Flexe article and trying to use it. I appreciate you trying to reproduce the results obtained by the experiments. This makes me very happy! To answer your questions: Q1: FLEXE and PYFLEX project is install based on windows or linux ? The installation is based on Linux. I tried to make a Windows version, but I only got good results with OmNet++ installed together with WSL (Windows Subsystem for Linux). I recommend installing it using Ubuntu and OmNet++ version 5.7
> 
> Q2: In readme : The project was partitioned into two, one of which is responsible for vehicle-to-vehicle communication ([Flexe] and the other for the construction and training of models ([PYFlexe] . i'm not sure how to create connection for two project . PyFlexe is responsible for training the models and Flexe is the vehicle communication part, as you mentioned. In the original article, I used openCV to create the models, you can access this version, it is still available on my github. However, in the most recent version, I use GRPC to connect PyFlexe with Flexe and use one part in Python and the other in Veins.
> 
> To run the project, you first need to run PyFlexe (server.py) and then Flexe. It is important that they are configured on the same port.

**Comment by LiHongyuan1** [comment]
> I will make a new update of the codes during this week. I am finishing an article about the new version of Flexe and I will make the new codes available, I believe it can solve some problems of running Flexe and PyFlexe together.

wow ,   i'm  really looking forward to your new version.

**Comment by LiHongyuan1** [comment]
> Hi! @LiHongyuan1! First of all, thank you very much for reading the Flexe article and trying to use it. I appreciate you trying to reproduce the results obtained by the experiments. This makes me very happy! To answer your questions: Q1: FLEXE and PYFLEX project is install based on windows or linux ? The installation is based on Linux. I tried to make a Windows version, but I only got good results with OmNet++ installed together with WSL (Windows Subsystem for Linux). I recommend installing it using Ubuntu and OmNet++ version 5.7
> 
> Q2: In readme : The project was partitioned into two, one of which is responsible for vehicle-to-vehicle communication ([Flexe] and the other for the construction and training of models ([PYFlexe] . i'm not sure how to create connection for two project . PyFlexe is responsible for training the models and Flexe is the vehicle communication part, as you mentioned. In the original article, I used openCV to create the models, you can access this version, it is still available on my github. However, in the most recent version, I use GRPC to connect PyFlexe with Flexe and use one part in Python and the other in Veins.
> 
> To run the project, you first need to run PyFlexe (server.py) and then Flexe. It is important that they are configured on the same port.

thanks for your reply so quickly .  i got it ~
