### ISSUE TITLE
How to run flexe project in OMNeT

### ISSUE THREAD

**Issue by LiHongyuan1** [WellingtonLobato/flexe#5]
Dear WellingtonLobato:

        Sorry to disturb you . i have install  OMNeT++ 5.7.0 n Ubuntu   ( USING WINDOWS SUBSYSTEM FOR LINUX (WSL2) , and Verifying the Installation success .  

    in your readme : Import the project into your OMNeT++ IDE workspace by clicking File > Import > General: Existing Projects into Workspace and selecting the directory you unpacked the Flexe module to.

   this is my step :  
1: git clone https://github.com/WellingtonLobato/flexe.git
2: conan install . --build missing -s compiler.version=10 -s compiler.libcxx=libstdc++11     
    this step have some issue and sloution as below 
![image](https://github.com/user-attachments/assets/25533ec6-3c79-43d3-96cd-e9846828357c)

[conan_log.txt](https://github.com/user-attachments/files/17539809/conan_log.txt)

 3: start omnet and choose flexe as workspace 
![image](https://github.com/user-attachments/assets/c12b2849-53ae-4c4b-a078-954ae11af4e3)

The question I would like to ask you is:
1:  does my step  delete conan.lock   and  generate default build profile  **is right** ?
2:  open porject is right ? in omnet IDE how to run project Simulation  ?

**Comment by LiHongyuan1** [comment]
(flexe) lhy@LiHongyuan:~/flexe$ ls
CONTRIBUTING.md  Makefile   conan.lock          conanbuildinfo.txt  conaninfo.txt  graph_info.json  simulations
COPYING.md       README.md  conanbuildinfo.mak  conanfile.txt       flexe.proto    img              src

this is my flexe folder file  after execute "delete conan.lock and generate default build profile "  command

**Comment by LiHongyuan1** [comment]
Another important question is  
Does Flexe  and Pyflex need  create  two  Conda vitrual environment  deploy or in same vitrual environment  still work?
because i found that some python library have conflict   such as  protobuf  .

**Comment by WellingtonLobato** [comment]
Hi @LiHongyuan1! 😁

It's interesting that you're using the Flexe and PyFlexe version with WSL2, I also use it in my Windows environment.
1) Regarding the question about deleting conan.lock, I didn't do that during the installation 🤔, but I see that, in your case, it worked.
2) Regarding the project, you still need to import veins.
I left the version I use here: https://github.com/user-attachments/files/16582603/veins-veins-5.2.zip and reference the Veins project in Flexe. (I intend to attach it along with Flexe).
3) No, you can only use one Conda environment. Regarding the versions, you can use similar versions of Protobuf without any problems. In my current setup, I have grpc/1.38.1, protobuf/3.17.1 (on Flexe side) and protobuf==3.20.0, grpcio==1.59.0 (on PyFlexe side)

**Comment by LiHongyuan1** [comment]
> Hi @LiHongyuan1! 😁
> 
> It's interesting that you're using the Flexe and PyFlexe version with WSL2, I also use it in my Windows environment.
> 
> 1. Regarding the question about deleting conan.lock, I didn't do that during the installation 🤔, but I see that, in your case, it worked.
> 2. Regarding the project, you still need to import veins.
>    I left the version I use here: https://github.com/user-attachments/files/16582603/veins-veins-5.2.zip and reference the Veins project in Flexe. (I intend to attach it along with Flexe).
> 3. No, you can only use one Conda environment. Regarding the versions, you can use similar versions of Protobuf without any problems. In my current setup, I have grpc/1.38.1, protobuf/3.17.1 (on Flexe side) and protobuf==3.20.0, grpcio==1.59.0 (on PyFlexe side)

**Comment by LiHongyuan1** [comment]
> > Hi @LiHongyuan1! 😁
> > It's interesting that you're using the Flexe and PyFlexe version with WSL2, I also use it in my Windows environment.
> > 
> > 1. Regarding the question about deleting conan.lock, I didn't do that during the installation 🤔, but I see that, in your case, it worked.
> > 2. Regarding the project, you still need to import veins.
> >    I left the version I use here: https://github.com/user-attachments/files/16582603/veins-veins-5.2.zip and reference the Veins project in Flexe. (I intend to attach it along with Flexe).
> > 3. No, you can only use one Conda environment. Regarding the versions, you can use similar versions of Protobuf without any problems. In my current setup, I have grpc/1.38.1, protobuf/3.17.1 (on Flexe side) and protobuf==3.20.0, grpcio==1.59.0 (on PyFlexe side)

thanks for your quick reply . you means that you can deploy Flexe and Pyflexe all in windows11 and work ?

for you answer  : 
1: my step is  Download veins.zip and  uzip into flexe root folder .  this project struct as below is right ? i'm not sure
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/34d90527-72cf-44ea-b5a5-daac22514b53">
2: if use one Conda ENV . how two create two different protobuf version ? because GRPC and tensorflow=2.11.0 need two conflict protobuf version. 
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/2230e72d-3445-44bf-92d0-e209e002cf9b">

3 : in Pyflexe project execute command error as below :  
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/df01a4a3-7201-46fe-a091-991c3681bd97">
maybe need pip install poetry . Does this library have any special version requirements?

**Comment by WellingtonLobato** [comment]
Hi @LiHongyuan1 

>>you means that you can deploy Flexe and Pyflexe all in windows11 and work ?
A: You can use WSL to install both Flexe and PyFlexe. Another alternative I tried was to install PyFlexe on Windows and communicate with Flexe via SSH.

1)my step is Download veins.zip and uzip into flexe root folder . this project struct as below is right ? i'm not sure
A: You can place it inside the project, as long as you reference it in Omnet++. I usually place it outside the project to keep it separate.

2) if use one Conda ENV . how two create two different protobuf version ? because GRPC and tensorflow=2.11.0 need two conflict protobuf version.
A: Yes, the tensorflow protobuf is different, but you can still use tensorflow version 2.11.0. In order to help, I will leave here my pip freeze of the environment where I run Flexe and PyFlexe.
```
absl-py==2.1.0
astunparse==1.6.3
bottle==0.12.25
cachetools==5.3.2
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
colorama==0.4.6
conan==1.58.0
contourpy==1.1.1
cryptography==41.0.7
cycler==0.12.1
distro==1.7.0
fasteners==0.19
flatbuffers==23.5.26
fonttools==4.51.0
gast==0.4.0
google-auth==2.27.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.60.1
grpcio-tools==1.60.1
h5py==3.10.0
idna==3.6
importlib-metadata==7.0.1
importlib_resources==6.4.0
iterators==0.0.2
Jinja2==3.1.3
joblib==1.3.2
keras==2.11.0
kiwisolver==1.4.5
libclang==16.0.6
Markdown==3.5.2
MarkupSafe==2.1.5
matplotlib==3.7.5
node-semver==0.6.1
numpy==1.24.4
oauthlib==3.2.2
opencv-python==4.9.0.80
opt-einsum==3.3.0
packaging==23.2
pandas==2.0.3
patch-ng==1.17.4
pickle5==0.0.11
pillow==10.2.0
pkg_resources==0.0.0
pluginbase==1.0.1
protobuf==3.20.1
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pycryptodome==3.20.0
Pygments==2.17.2
PyJWT==2.8.0
pyparsing==3.1.2
python-dateutil==2.8.2
pytz==2024.1
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.3.2
scipy==1.10.1
six==1.16.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.34.0
termcolor==2.4.0
threadpoolctl==3.2.0
tqdm==4.66.1
typing_extensions==4.9.0
tzdata==2024.1
urllib3==1.26.18
Werkzeug==3.0.1
wrapt==1.16.0
zipp==3.17.0
```

3)in Pyflexe project execute command error as below :
A: Is this the PyFlexe or Flexe folder? If it is the PyFlexe folder, you can run the command: `python server_flexe.py --ip 127.0.0.1:5000 --dataset MNIST
`

If you like, we can arrange a meeting. I can try to help further with the installation.

**Comment by LiHongyuan1** [comment]
> Hi @LiHongyuan1
> 
> > > you means that you can deploy Flexe and Pyflexe all in windows11 and work ?
> > > A: You can use WSL to install both Flexe and PyFlexe. Another alternative I tried was to install PyFlexe on Windows and communicate with Flexe via SSH.
> 
> 1)my step is Download veins.zip and uzip into flexe root folder . this project struct as below is right ? i'm not sure A: You can place it inside the project, as long as you reference it in Omnet++. I usually place it outside the project to keep it separate.
> 
> 2. if use one Conda ENV . how two create two different protobuf version ? because GRPC and tensorflow=2.11.0 need two conflict protobuf version.
>    A: Yes, the tensorflow protobuf is different, but you can still use tensorflow version 2.11.0. In order to help, I will leave here my pip freeze of the environment where I run Flexe and PyFlexe.
> 
> ```
> absl-py==2.1.0
> astunparse==1.6.3
> bottle==0.12.25
> cachetools==5.3.2
> certifi==2024.2.2
> cffi==1.16.0
> charset-normalizer==3.3.2
> colorama==0.4.6
> conan==1.58.0
> contourpy==1.1.1
> cryptography==41.0.7
> cycler==0.12.1
> distro==1.7.0
> fasteners==0.19
> flatbuffers==23.5.26
> fonttools==4.51.0
> gast==0.4.0
> google-auth==2.27.0
> google-auth-oauthlib==0.4.6
> google-pasta==0.2.0
> grpcio==1.60.1
> grpcio-tools==1.60.1
> h5py==3.10.0
> idna==3.6
> importlib-metadata==7.0.1
> importlib_resources==6.4.0
> iterators==0.0.2
> Jinja2==3.1.3
> joblib==1.3.2
> keras==2.11.0
> kiwisolver==1.4.5
> libclang==16.0.6
> Markdown==3.5.2
> MarkupSafe==2.1.5
> matplotlib==3.7.5
> node-semver==0.6.1
> numpy==1.24.4
> oauthlib==3.2.2
> opencv-python==4.9.0.80
> opt-einsum==3.3.0
> packaging==23.2
> pandas==2.0.3
> patch-ng==1.17.4
> pickle5==0.0.11
> pillow==10.2.0
> pkg_resources==0.0.0
> pluginbase==1.0.1
> protobuf==3.20.1
> pyasn1==0.5.1
> pyasn1-modules==0.3.0
> pycparser==2.21
> pycryptodome==3.20.0
> Pygments==2.17.2
> PyJWT==2.8.0
> pyparsing==3.1.2
> python-dateutil==2.8.2
> pytz==2024.1
> PyYAML==6.0
> requests==2.31.0
> requests-oauthlib==1.3.1
> rsa==4.9
> scikit-learn==1.3.2
> scipy==1.10.1
> six==1.16.0
> tensorboard==2.11.2
> tensorboard-data-server==0.6.1
> tensorboard-plugin-wit==1.8.1
> tensorflow==2.11.0
> tensorflow-estimator==2.11.0
> tensorflow-io-gcs-filesystem==0.34.0
> termcolor==2.4.0
> threadpoolctl==3.2.0
> tqdm==4.66.1
> typing_extensions==4.9.0
> tzdata==2024.1
> urllib3==1.26.18
> Werkzeug==3.0.1
> wrapt==1.16.0
> zipp==3.17.0
> ```
> 
> 3)in Pyflexe project execute command error as below : A: Is this the PyFlexe or Flexe folder? If it is the PyFlexe folder, you can run the command: `python server_flexe.py --ip 127.0.0.1:5000 --dataset MNIST `
> 
> If you like, we can arrange a meeting. I can try to help further with the installation.

thanks , I am currently facing some installation issues.  you can arrange a meeting when you are free .  just send agenda for me  . by the way which meeting software are popular in Brazil and I installed it ahead of time.

**Comment by WellingtonLobato** [comment]
We can use the Google Meet. Send me a e-mail(wellington.lobato.junior@gmail.com), we can schedule a meeting. I just installed Flexe on a virtual machine with Ubuntu (I just did it right now). I will make it available in this issue and in the Flexe repository.

Also, thank you very much for (trying) using Flexe! 😀🤗 It's really nice when other researchers and developers use it.

**Comment by LiHongyuan1** [comment]
> We can use the Google Meet. Send me a e-mail([wellington.lobato.junior@gmail.com](mailto:wellington.lobato.junior@gmail.com)), we can schedule a meeting. I just installed Flexe on a virtual machine with Ubuntu (I just did it right now). I will make it available in this issue and in the Flexe repository.
> 
> Also, thank you very much for (trying) using Flexe! 😀🤗 It's really nice when other researchers and developers use it.

okay , i just send email for you .
